### ISSUE TITLE
IO Type -> Type

### ISSUE THREAD

**Issue by CSuerig** [ob-fun-ws17/studienarbeit-haskell_io#1]
Sehr geehrter Herr Braun, 
in unserem Projekt möchten wir Filenamen aus einem Directory (mittels listDirectory) einlesen und anschließend mit den eingelesenen Namen arbeiten. Leider ist uns dies aber nicht möglich, da der Typ innerhalb einer IO Monade zurück gegeben wird. Leider gibt es danach aber keine Möglichkeit mit den Typen, welche in der Monade eingefasst sind, zu arbeiten, also beispielsweise String operationen auf ihnen auszuführen. Auch ist es uns nicht gelungen die Typen aus der Monade zu extrahieren. 
Wissen Sie eine möglichkeit, wie man am besten mit Typen in Monaden arbeiten kann? 

Beispielsweise:
 
listDirectory :: FilePath -> IO [FilePath]

Wir möchten auf elemente des Ergebnisses (IO [FilePath]) allerdings gerne die Funktionen
dropFileName :: FilePath -> FilePath
takeBaseName:: FilePath -> FilePath 
takeExtension:: FilePath -> FilePath

anwenden.  (Siehe SRC/Core.hs) 

Viele Grüße

Andreas Moser, Christoph Sürig

**Comment by obcode** [comment]
Sie müssen das nur anders herum denken, also aus der IO-Monade aufrufen, z.B.

```haskell
f fp = do
  dirs <- listDirectory fp
  let filename' = map dropFileName ...
```

Raus kommen Sie nicht mehr, aber Sie können ja Funktionen definieren, die einen `FilePath` nehmen und irgendetwas zurück geben und das dann aufrufen.

HTH

**Comment by obcode** [comment]
z.B. so (*untested*):

```haskell
getPhotos :: FilePath -> String -> [PhotoFile]
getPhotos path extension = map toPhotoFile $ getMocks path extension

toPhotoFile :: FilePath -> PhotoFile
toPhotoFile file = PhotoFile
  { path = dropFileName file
  , fileName = takeBaseName file
  , fileExtension = takeExtension file
  }

getMocks :: FilePath -> String -> [FilePath]
getMocks path extension =
  [ path ++ "/" ++ "a" ++ extension
  , path ++ "/" ++ "b" ++ extension
  , path ++ "/" ++ "c" ++ extension
  , path ++ "/" ++ "d" ++ extension
  ]

getFileList :: FilePath -> [FilePath]
getFileList = listDirectory

getPhotosFromPath FilePath -> String -> IO [PhotoFile]
getPhotosFromPath fp extension = do
  files <- getFileList fp
  return $ map (`getPhotos` extension) files
```

**Comment by CSuerig** [comment]
Vielen Dank für die schnelle Antwort, sie hat uns bis zu einem Gewissen Punkt sehr weitergeholfen.
Doch nun sind wir an einer Stelle angelangt, an welcher wir aus einer Monade heraus eine Funktion, in einer anderen Monade aufrufen möchten. 

Das Problem hierbei ist, dass dadurch die eine IO Monade innerhalb der anderen wäre, was so aber nicht funktioniert (Funktionen InputHandler und calcDifference)

Hätten Sie diesbezüglich noch einen Tipp für uns, oder sollten wir unseren Architekturansatz überdenken?

```Haskell
Cmd.hs:

inputHandler :: (PhotoSetting, String) -> IO ()
inputHandler (settings, message) = do
  hSetBuffering stdout NoBuffering
  putStrLn message
  input <- readLn :: IO String
  if input == "quit"
    then putStrLn "Beenden ..."
    else inputHandler (handleCommand (toTuple input) settings)

handleCommand :: (String, String) -> PhotoSetting ->(PhotoSetting,String)
handleCommand("showDifference",_) settings = (settings,calcDifference settings)

calcDifference ::  PhotoSetting -> IO String
calcDifference  settings = do
   list <- loadAndGetDifference settings
   let message = concat (map fileName list)
   return message

Core.hs:

loadAndGetDifference :: PhotoSetting -> IO [PhotoFile]
loadAndGetDifference settings = do
  jpegs <- listDirectory $ toFilePath (jpegPath settings)
  raws <- listDirectory $ toFilePath (rawPath settings)
  let jpegFotoFile = filter (\x -> fileExtension x == jpegEnding settings)(map toPhotoFile jpegs)
  let rawFotoFile = filter (\x -> fileExtension x == rawEnding settings)(map toPhotoFile raws)
  return $ rawFotoFile \\ jpegFotoFile
```

**Comment by obcode** [comment]
`handleCommand` müsste dann auch IO machen, also z.B. (*untested*):

```haskell
inputHandler :: (PhotoSetting, String) -> IO ()
inputHandler (settings, message) = do
  hSetBuffering stdout NoBuffering
  putStrLn message
  input <- readLn :: IO String
  if input == "quit"
    then putStrLn "Beenden ..."
    else do
      result <- handleCommand (toTuple input) settings
      inputHandler result

handleCommand :: (String, String) -> PhotoSetting -> IO (PhotoSetting,String)
handleCommand("showDifference",_) settings = do
  diff <- calcDifference settings
  return (settings, diff)
```

HTH

**Comment by CSuerig** [comment]
Vielen Dank hat uns sehr weitergeholfen.
